### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by nickmwhite** [kissmetrics/km-support#105]
You recommend that we go to a URL at the end, but the URL is broken :-/

This is the URL I'm referring to: http://support.kissmetrics.com/misc/event-library

**Comment by percyhanna** [comment]
Where are you seeing this link? I could not find it anywhere.

**Comment by nickmwhite** [comment]
At the end of this video: http://support.kissmetrics.com/tutorial/event-library-tutorial/index.html

**Comment by percyhanna** [comment]
Ah thanks, that's why I couldn't find it. :) Addressing the issue shortly.

**Comment by percyhanna** [comment]
Thanks for bringing this to our attention. It should now be resolved by #106.

**Comment by nickmwhite** [comment]
You bet.
