### ISSUE TITLE
Docs: Callback with Custom Event

### ISSUE THREAD

**Issue by jonazri** [kissmetrics/km-support#11]
I'm using jQuery.trigger() to fire an event when the KM object is ready. That allows me to wrap code that needs a callback in a jQuery ready function. I could see this method being really useful to folks so you may want to add to documentation on callbacks if you agree.

Step 1: Trigger the event right after the Kissmetrics Library Call:

``` javascript
_kmq.push(function() {
    $.event.trigger("kmLoaded");
});
```

Step 2: For stuff that requires the KM object to be ready, wait for that custom event:

``` javascript
$("body").on("kmLoaded", function() {
   doStuff;
});
```

Another idea would be to fire your own events as part of the Kissmetrics library, then provide documentation so users know what events they can bind to.

**Comment by eskfung** [comment]
Is this primarily to add abstraction to waiting for when the KM object is ready?

``` javascript
_kmq.push(function() {
    $.event.trigger("kmLoaded");
    // This function executes *because* KM has loaded
    // why not doStuff here?
});
```

**Comment by jonazri** [comment]
In my particular use case, the abstraction provides better interoperability with my tag management platform's script firing conditions and (I think?) some timing / performance benefits as well. 

BrightTag, the tag manager we are using, manages all events and data in one place to determine the conditions when any particular code block will execute without placing the entire burden on client-side JS. For my use it's convenient and efficient to have an event to bind to because there's a place for event firing conditions in their interface and their system deals with code optimization for me.

In general and for users with a more traditional setup, I would imagine pushing heavy functions to _kmq being something that slow things down a bit... but I'm by no means an expert in these things. Just figured others could find this useful if they either use a 3rd party tag manager, or if they would like timing to be managed outside of KM.

**Comment by eskfung** [comment]
Ah, good point. If tag managers get involved, I can see how this would be useful.

I can incorporate your explanation into an alternate version of http://support.kissmetrics.com/apis/javascript/javascript-specific/#callback-functions

**Comment by eskfung** [comment]
https://github.com/kissmetrics/km-support/commit/071c6a1775ff4cd89a2b2e4c03c59001f5a497fc

**Comment by woutersmet** [comment]
Just wanna say that I was halfway through typing my request to support when I ran into the part in the kissmetrics docs where it said  this trick. It's exactly what I needed and for similar reasons, so thanks both @eskfung and @jonazri!
