### ISSUE TITLE
Offset and limit parameter not work

### ISSUE THREAD

**Issue by loduis** [kissmetrics/km-support#116]
http://support.kissmetrics.com/api-update.html#request-3

For this query:
https://query.kissmetrics.com/v2/queries/6ba99c31-1456-4684-8d2b-29ba09670ca9/results?offset=50&limit=50

Response is

```
{
    "meta":{
      "status":400,
      "message":":offset must be an integer",
      "errors":"invalid_parameter"]
    },
    "links":[]
}
```

offset is integer

**Comment by eskfung** [comment]
@loduis I'm seeing the same issues with getting paginated results. Let me escalate to our API team. Thanks for the heads up.

**Comment by percyhanna** [comment]
Thanks for bringing this to our attention. We have a fix for this that we are working to get out ASAP.

**Comment by percyhanna** [comment]
@loduis This issue should now be resolved. Please let us know if you run into any other problems. Thanks!

**Comment by loduis** [comment]
Yes, this work now
