### ISSUE TITLE
PHP documentation outdated

### ISSUE THREAD

**Issue by DataTables** [kissmetrics/km-support#117]
I might be missing something, but the [PHP API documentation](http://support.kissmetrics.com/apis/php/) points to [the kissmetrics/kissmetrics-php repo](https://github.com/kissmetrics/kissmetrics-php). However, the API described in the documentation doesn't appear to resemble the API in the code at all. For example there is no `KM` class, nor even a `km.php` file.

Is it possible to have the [PHP API doc](https://github.com/kissmetrics/km-support/blob/gh-pages/_posts/2013-04-18-php.md) updates to reflect the current API?

**Comment by percyhanna** [comment]
@eskfung The link on our support page points to our new PHP library, but still documents the [old PHP interface](https://github.com/kissmetrics/KISSmetrics/blob/master/km.php). I'm thinking we could update the [main PHP docs page](https://github.com/kissmetrics/km-support/blob/gh-pages/_posts/2013-04-18-php.md) to use our new PHP library, but have a link to an archived version of the docs that shows the old specs. Thoughts?

**Comment by eskfung** [comment]
@percyhanna :+1:, gotta get familiar with the new PHP interface. Will try to get this finished by the end of the week.

**Comment by eskfung** [comment]
@DataTables thank you for the feedback! I am reusing the examples included in the kissmetrics-php README, so please let us know if that is not sufficient.

**Comment by DataTables** [comment]
I have two suggestions to improve the documentation shown there if I may:
1. Include instructions on how to include the library files. Its a simple `require` statement in PHP, but at the moment you need to include the files individually and in a particular order. I've just sent a [pull request](https://github.com/kissmetrics/kissmetrics-php/pull/17) which makes is a single one line include, but I would still recommend including that in the documentation - `require( 'KISSMetrics/KM.php' );` if you accept my pull request.
2. The line `>alias('old-anonymous-cookie')` appears to be meaningless. The string value given has no particular value - what we need is the anonymous cookie value. I've used the following for that (although I'm not 100% certain that this is the correct way to do it):

``` php
            if ( isset( $_COOKIE['km_ai'] ) ) {
                $km->alias( $_COOKIE['km_ai'] );
            }
```

The server-side libraries are presumably used primarily for triggering events on the sever-side only so hopefully this will make it a little bit easier for people new to KISSMetrics such as myself to get going with it if they are using PHP.

**Comment by percyhanna** [comment]
@DataTables thanks for the suggestions, I think those seem quite reasonable. @eskfung could you take a look at updating the examples as well?
