### ISSUE TITLE
people_v3_search custom date ranges not working

### ISSUE THREAD

**Issue by dennis-zinzi** [kissmetrics/km-support#150]
In the previous version of the people search API (people_v2_search) the following query worked successfully, and gave me the correct results:

``` bash
curl -i 'https://query.kissmetrics.com/v2/products/PRODUCT-ID/reports/REPORT-ID/run'  \
  -H 'Authorization: Bearer MY-API-TOKEN'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json'  \
  -X POST  \
  -d '{"start_date": "START-DATE", "end_date": "END-DATE"}'
```

where the start_date and end_date data is in the ISO 8601 format (e.g.: 2016-05-14T00:00:00+01:00)

Now that some of our products only have reports of type _people_v3_search_, the request above seems to ignore the data sent with the request (start_date & end_date), and just default to the date parameters set to in the kissmetrics reports admin/website.

I've also tried to use the alleged new format to run the report (retrieved using the _products/PRODUCT-ID/reports_ request on the product):

``` bash
curl -i 'https://api.kissmetrics.com/query/reports/REPORT-ID/run'  \
  -H 'Authorization: Bearer MY-API-TOKEN'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json'  \
  -X POST  \
  -d '{"start_date": "START-DATE", "end_date": "END-DATE"}'
```

And it always returns:

``` bash
{"meta":{"status":400,"message":"Error initializing report: Only people search reports supported at this time.","errors":["bad_request"]},"links":[]}
```

I was wondering if the request parameters have changed/the way I built the request is now wrong and if there is any documentation on how to run the new **people_v3_search** reports that you can point me to for any reference (as I failed to find one anywhere).

Hope you can help,
Dennis

**Comment by NathanielWroblewski** [comment]
Hello, Dennis.  I'd be happy to help you.  

You are correct that `start_date` and `end_date` parameters are ignored for new people search reports.  When running against the saved report endpoint, these parameters are fetched from the saved report directly.  If you are trying to programmatically change and run a report, I'd recommend the adhoc report endpoint.  The adhoc endpoint will pull all query information from parameters instead of pulling from the saved report.  To hit the adhoc endpoint:

``` sh
curl -i 'https://query.kissmetrics.com/v2/products/PRODUCT_GUID/reports/people_search' \
  -H 'Authorization: Bearer YOUR-API-TOKEN'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json'  \
  -X POST  \
  -d QUERY_PARAMS
```

The easiest way to obtain the `QUERY_PARAMS` is by copying them from the browser console after you run a report.  You could programmatically generate the json too, but we don't have any documentation for that just yet.

![redacted](https://cloud.githubusercontent.com/assets/2602872/16204555/12b12aae-36e5-11e6-9654-1dc9eb4705db.jpg)

When you've copied the query params, you should see that they look roughly like this:

``` js
{
  "sort": "0",
  "order": "asc",
  "product_id": "65faf01a-aaaa-0000-9999-555555555555",
  "query_params": {
    "type": "group",
    "filter": {
      "type": "and",
      "operands": [
        {
          "type": "event",
          "negate": false,
          "event": 123,
          "frequencyValue": 1,
          "frequencyOccurrence": "at_least",
          "dateRange": {
            "dateRangeId": "custom",
            "startDate": "2015-10-26",
            "endDate": "2015-11-24"
          },
          "comparisonMode": "any_value"
        }
      ],
      "version": 2,
      "options": {
        "defaultDateRange": {
          "dateRangeId": "custom",
          "startDate": "2015-10-26",
          "endDate": "2015-11-24"
        }
      }
    },
    "calculations": []
  }
}
```

At this point, changes you make to the `startDate` and `endDate` parameters will change the query.

The response from running the report will include the query id, which you can use to lookup the query status at `GET /v2/queries/QUERY_ID/status`.  Once the status indicates that the query has finished, you can lookup results at `GET /v2/queries/QUERY_ID/results`.

We are also planning a V3 release which will simplify this process.

Let me know if you have any questions.

**Comment by dennis-zinzi** [comment]
Hello Nathaniel, thank you for the reply, I've tried hitting the endpoint you've suggested, but I am getting a 500 Internal Server Error, is this an issue with the endpoint, or am I still missing something in the request.

``` bash
curl -i 'https://query.kissmetrics.com/v2/products/PRODUCT-ID/reports/people_search' \
   -H 'Authorization: Bearer MY-API-TOKEN' \
   -H 'Accept: application/json' \
   -H 'Content-Type: application/json' \
   -X POST \
   -d '{"options":{"defaultDateRange":{"dateRangeId":"custom","startDate":"2016-06-20T00:00:00+01:00","endDate":"2016-06-21T00:00:00+01:00"}}}'
```

In case not all the query parameters have to be set I have also tried the request:

``` bash
curl -i 'https://query.kissmetrics.com/v2/products/PRODUCT-ID/reports/people_search' \
   -H 'Authorization: Bearer MY-API-TOKEN' \
   -H 'Accept: application/json' \
   -H 'Content-Type: application/json' \
   -X POST \
   -d '{"startDate":"2016-06-20T00:00:00+01:00","endDate":"2016-06-21T00:00:00+01:00"}'
```

In a desperate attempt I also tried copying all of the query parameters (retrieved when running the report successfully in the browser/your website):

``` bash
curl -i 'https://query.kissmetrics.com/v2/products/PRODUCT-ID/reports/people_search' \
   -H 'Authorization: Bearer MY-API-TOKEN' \
   -H 'Accept: application/json' \
   -H 'Content-Type: application/json' \
   -X POST \
   -d '{"type":"group","filter":{"type":"and","operands":[{"type":"event","negate":false,"event":1,"frequencyValue":1,"frequencyOccurrence":"at_least","dateRange":{"dateRangeId":"custom","startDate":"2016-06-20","endDate":"2016-06-21"},"comparisonMode":"any_value"}],"dateRange":{"dateRangeId":"last_7_days"},"version":2,"options":{"defaultDateRange":{"dateRangeId":"custom","startDate":"2016-06-20","endDate":"2016-06-21"}}},"calculations":[]}'
```

In all cases the endpoint has returned the following:

``` bash
{"status":"500","error":"Internal Server Error"}
```

Could you please me know if I am missing an additional header, or if the query isn't constructed properly.

Or if there is an issue when hitting your endpoint, as the error suggests, could you please look into it, and let me know when you manage to resolve it.

Many thanks,
Dennis

**Comment by percyhanna** [comment]
Hi Dennis,

We'll look to improve the error message that you're currently getting on that endpoint.

For now, the problem is that you need to send the params to the endpoint exactly as it's done in our app. The main issue is that you need to nest the query params inside a `query_params` key:

``` json
{
  "query_params": {
    "type": "group",
    "filter": {
      "type": "and",
      "operands": [
        {
          "type": "event",
          "negate": false,
          "event": 1,
          "frequencyValue": 1,
          "frequencyOccurrence": "at_least",
          "dateRange": {
            "dateRangeId": "custom",
            "startDate": "2016-06-20",
            "endDate": "2016-06-21"
          },
          "comparisonMode": "any_value"
        }
      ],
      "dateRange": {
        "dateRangeId": "last_7_days"
      },
      "version": 2,
      "options": {
        "defaultDateRange": {
          "dateRangeId": "custom",
          "startDate": "2016-06-20",
          "endDate": "2016-06-21"
        }
      }
    },
    "calculations": []
  }
}
```

Once you do that, it should work for you.

**Comment by dennis-zinzi** [comment]
**EDIT :** Upon further inspection, I noticed I missed one of the keys ("event") inside the _query_params_, and once included, everything works as expected.

Hello Nathaniel & Andrew,

I have done as you suggested and included the full query_params payload, and the endpoint finally returns a status URL as expected.

``` bash
curl -i 'https://query.kissmetrics.com/v2/products/PRODUCT-ID/reports/people_search' \
   -H 'Authorization: Bearer MY-API-TOKEN' \
   -H 'Accept: application/json' \
   -H 'Content-Type: application/json' \
   -X POST \
   -d '{"query_params":{"type":"group","filter":{"type":"and","operands":[{"type":"event","negate":false,"frequencyValue":1,"frequencyOccurrence":"at_least","dateRange":{"dateRangeId":"custom","startDate":"2016-06-20","endDate":"2016-06-21"},"comparisonMode":"any_value"}],"dateRange":{"dateRangeId":"last_7_days"},"version":2,"options":{"defaultDateRange":{"dateRangeId":"custom","startDate":"2016-06-20","endDate":"2016-06-21"}}},"calculations":[]}}'
```

Returns: 

``` bash
{"meta":{"status":202},"data":{"message":"success"},"links":[{"name":"Status","rel":"query-status","href":"https://query.kissmetrics.
com/v2/queries/QUERY-ID/status","templated":false}]}
```

The issue I've been presented with now is, that I am unable to send a request to that URL, as it is always returning the same server error, telling me the query has been cancelled. Could you let me know if the headers needed have changed, if the way the request is sent is different (POST instead of GET?), or if this is an error with the endpoint it.

This is what I send (which works for people_search_v2):

``` bash
curl -i 'https://query.kissmetrics.com/v2/queries/QUERY-ID/status' \
   -H 'Authorization: Bearer MY-API-TOKEN' \
   -H 'Accept: application/json' \
   -H 'Content-Type: application/json'
```

And the response I always get is:

``` bash
{"meta":{"status":500,"message":"This query has been canceled","errors":["server_error"]},"links":[]}
```

Many thanks,
Dennis

**Comment by NathanielWroblewski** [comment]
Awesome!  Glad to hear everything is working for you.  If you have any other questions, let us know!

**Comment by percyhanna** [comment]
Sorry, I missed your edit! Looks like you've got it all figured out.
