### ISSUE TITLE
Link tracking in pages/posts

### ISSUE THREAD

**Issue by geniuswebtools** [kissmetrics/km-support#18]
The regex that's putting the script tag after the a tags are causing issues w/ some other JavaScripts.

Can this be changed so that instead of a tag followed by script tag, that at the end of the content a single script tag is placed w/ each of the push calls foreach of the matched links in the content?

**Comment by percyhanna** [comment]
Hi Marion,

I've asked @eskfung to look into this issue for you.

Thanks,
-Percy

**Comment by eskfung** [comment]
Hello Marion,

I'm not sure which regex you're referring to. Is there a code snippet you are referring to?

-Eric

**Comment by geniuswebtools** [comment]
In function the_content( $text ) there is a condition to track the links.

``` php
// Track all links
            if( get_option( 'kissmetrics_track_links' ) )
                $text = preg_replace_callback( KM_Filter::$link_regex, array( 'KM_Filter', 'parse_content_link' ), $text );
```

... this renders:

`<a href="#">hypertext</a>`
... as ... 
`<a href="#">hypertext</a><script> /*kissmetrics*/ </script>`

... and because that change in the HTML it's preventing another jQuery plugin from working.  My suggestion is, that instead of modifying the HTML take the links that are found in the content, and put the kissmetrics push methods in one one script container at the end of the content.

**Comment by eskfung** [comment]
Ah, you're referring to our WordPress plugin. I'll dive a little deeper on how we can implement your suggestion.

**Comment by geniuswebtools** [comment]
Did I ask this in the wrong location?  I don't remember what lead me here, but at the time this made the logical sense to request the change.

**Comment by eskfung** [comment]
No worries, this place is fine. I realized our WordPress plugin isn't on Github, which I think we should put up this week.

**Comment by eskfung** [comment]
Resolving in the km-wordpress repo.
