### ISSUE TITLE
Add swiftype include data-attribute

### ISSUE THREAD

**Issue by derekpcollins** [kissmetrics/km-support#4]
Add swiftype include data-attribute to main column; remove all other swiftype exclude data-attributes

**Comment by jasoncaldwell** [comment]
Adding to Derek's comment: https://swiftype.com/documentation/content_inclusion_exclusion

**Comment by eskfung** [comment]
Added the attribute in https://github.com/kissmetrics/km-support/commit/adce52c7d16fc3911af5cb7b6304f97b30123272
