### ISSUE TITLE
Tracking forms submitted via jQuery - scanning for <input>'s

### ISSUE THREAD

**Issue by eskfung** [kissmetrics/km-support#5]
Looking at the source of the tracking script, one could adapt our helper functions to replicate our trackSubmit function, but in jQuery:

```
$('form').submit(function(event) {  // modify the jQuery selector if needed
  var props = {'foo':'bar'};  // define any initial KM properties here
  if ( typeof(KM_SKIP_FORM_FIELDS) == 'undefined' || !KM_SKIP_FORM_FIELDS)
    {
      var form;
      // KM.sre(event) finds the originating element that triggered an event
      if ( form = KM.sre(event) )
        // KM.fp(form) returns the hash of properties found from scanning the form inputs
        // KM.mg(hash1, hash2) merges two hashes together
        props = KM.mg(props, KM.fp(form));
    }
  KM.record('Form Submitted', props)  // indicate the name of the KM event to record
});
```

The question is whether we ought to support calling our helper functions directly.

**Comment by mstump** [comment]
If it's really an issue lets promote the functionality to a top level function. I don't want users calling helper functions. How often is this requested?

**Comment by eskfung** [comment]
In particular, this specifically has not been very much requested. However, Nate and I had discussed adding jQuery to our library, though we were worried about compatibility issues if someone's loading a different version of jQuery in a separate library, even if we load it with noConflict.

**Comment by eskfung** [comment]
Wrong repo.
