### ISSUE TITLE
No link to download the JavaScript library

### ISSUE THREAD

**Issue by dpashkevich** [kissmetrics/km-support#78]
There's a little documentation page about hosting the JavaScript library yourself, but no download links (and possibly extra instructions on including it in the page) are provided.

https://github.com/kissmetrics/km-support/blob/gh-pages/_posts/2012-10-19-hosting-js-yourself.md

**Comment by eskfung** [comment]
In the JavaScript snippet we provide, you are able to assemble the URL of the JavaScript file with your API key:

https://doug1izaerwt3.cloudfront.net/REPLACE_WITH_YOUR_API_KEY.1.js

Downloading the JS file is as straightforward as visiting that URL and having your browser 'Save Page As...'.

**Comment by dpashkevich** [comment]
Thanks! I just wasn't sure if there's a special version for downloading
that's somehow different.
You may want to be a bit more explicit in the docs about that.

On Mon, Oct 13, 2014 at 12:05 PM, Eric Fung notifications@github.com
wrote:

> In the JavaScript snippet we provide, you are able to assemble the URL of
> the JavaScript file with your API key:
> 
> https://doug1izaerwt3.cloudfront.net/REPLACE_WITH_YOUR_API_KEY.1.js
> 
> Downloading the JS file is as straightforward as visiting that URL and
> having your browser 'Save Page As...'.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kissmetrics/km-support/issues/78#issuecomment-58931290
> .

## 

Dmitry Pashkevich

**Comment by eskfung** [comment]
That's fair; I will add that today. Thanks for the tip!

**Comment by eskfung** [comment]
Included in https://github.com/kissmetrics/km-support/commit/c30797d5238474b2343b1b6c62f0235ced374fdc

**Comment by dpashkevich** [comment]
Sweet, thanks!

On Mon, Oct 13, 2014 at 12:27 PM, Eric Fung notifications@github.com
wrote:

> Included in c30797d
> https://github.com/kissmetrics/km-support/commit/c30797d5238474b2343b1b6c62f0235ced374fdc
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kissmetrics/km-support/issues/78#issuecomment-58934205
> .

## 

Dmitry Pashkevich
