### ISSUE TITLE
Revenue report has broken links

### ISSUE THREAD

**Issue by whatcould** [kissmetrics/km-support#80]
I was trying to figure out how churn is calculated; in the Quick Reference table, Churn is linked:
http://support.kissmetrics.com/tools/revenue-report.html#churn__what_about_customers_who_stop_paying ... but that link doesn't go anywhere.

The description of churn in that table reads, "How this is counted depends on whether you are using your report configurations." Whether or not I am using my report configuration? or HOW I am configuring the report? This is unclear.

**Comment by eskfung** [comment]
Aha, thanks for pointing this out. The table description is out of date with changes we made to the Revenue report.

In particular, you can choose the time period that matches your business case. Do you consider customers churned after 30 days of non-payment? Or 60 days? Or 90?

Additionally, you can select which of your KM events represents a direct cancelation, so if you have a 'Canceled' event, we can take that into account too.

More details at:
http://support.kissmetrics.com/tools/revenue-report.html#choosing-a-custom-churn-time-period
http://support.kissmetrics.com/tools/revenue-report.html#choosing-a-custom-churn-event
