### ISSUE TITLE
How much data will the iOS SDK store while offline?

### ISSUE THREAD

**Issue by JetForMe** [kissmetrics/km-support#87]
The nature of our app is such that users use it generally while disconnected from the 'Net. Are there any limits on how many events you'll store while offline, for later transmission?

**Comment by percyhanna** [comment]
I don't see anything that limits the size of the event queue in the SDK. This seems like a reasonable feature request. We should also update the documentation to reflect this.

**Comment by JetForMe** [comment]
Actually, I don't want to limit it. It's very likely our users will log many events before returning to connectivity.

> On Nov 12, 2014, at 17:17 , Andrew Hanna notifications@github.com wrote:
> 
> I don't see anything that limits the size of the event queue in the SDK. This seems like a reasonable feature request. We should also update the documentation to reflect this.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Rick Mann
rmann@latencyzero.com

**Comment by percyhanna** [comment]
Perfect, even better.

For reference, the code that archives the send queue: https://github.com/kissmetrics/KISSmetrics-iOS-SDK/blob/master/KISSmetricsAPI/KMAArchiver.m#L802-808

**Comment by percyhanna** [comment]
Updated in d0a1b63201e906eb241dd2948f61a68d1f5c06be.
